#spring.application.name=mallStore
#server.servlet.context-path=/store
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

    redis:
      host: localhost
      port: 6379
      database: 0
      # password: yourpassword


mybatis:
  mapper-locations: classpath:/mapper/*.xml


user:
  address:
    max-count: 20


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mallstore:
  expire-time: 7200